#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url: http://192.168.1.245:8082/artifactory/webapp-libs-snapshot-local/webapp.war
      dest: /root/
      url_username: admin
      url_password: P@ssw0rd

  - name: Rename .war Artifact
    command: mv webapp-1.0-RELEASE.war webapp.war
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: webapp`
      build:
        path: /root/
        pull: no
        args:
          listen_port: 8080
      source: build

#  - name: Log into DockerHub
#    docker_login:
#     username: rmspavan
#     password: P2$$w0rd

    
  - name: Push to docker registry
    docker_image:
      name: webapp
      repository: 192.168.1.212/webapp:1.0
      push: yes
      source: local
